# Configuration file

[settings]
nSteps = 500 # number of time steps
tEnd = 0.5 # specified end time

[geometry]
meshName = "bay.msh" # name of the computational mesh
borders = [[0.2, 0.5], [0.3, 0.6]] # borders of fishing grounds

[IO]
logName = "log_B" # name of the logfile
#writeFrequency = 20 