# Configuration file

[settings]
nSteps = 500 # number of time steps
tEnd = 0.5 # specified end time

[geometry]
meshName = "bay.msh" # name of the computational mesh
borders = [[0.0, 0.6], [0.0, 0.3]] # borders of fishing grounds

[IO]
logName = "log_C" # name of the logfile
#writeFrequency = 20 